version: '3.4'

services:
  mysql-m:
    image: mysql:5.7
    container_name: mysql-m
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    volumes:
      - master_data:/var/lib/mysql
      - ./master:/etc/mysql/conf.d

  mysql-s1:
    image: mysql:5.7
    container_name: mysql-s1
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3308:3306"
    volumes:
      - slave1_data:/var/lib/mysql
      - ./slave1:/etc/mysql/conf.d

  mysql-s2:
    image: mysql:5.7
    container_name: mysql-s2
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3309:3306"
    volumes:
      - slave2_data:/var/lib/mysql
      - ./slave2:/etc/mysql/conf.d

volumes:
  master_data:
  slave1_data:
  slave2_data:
